SF_ACCOUNT = "cob99909"
SF_USER = "StreamLit"
SF_PASSWORD = "@wDsjK1425%wfFG"
SF_ROLE = "ACCOUNTADMIN"
SF_DATABASE = "BAYPOINT"
SF_WAREHOUSE = "FINICITYSTREAMPROD"
SF_SCHEMA = "BCPFUNDS"

TRIDENT_LORENZ_USERNAME = "TRIDENT_LORENZ"
TRIDENT_LORENZ_PASSWORD =  "tridentLorenz123!"
